---
version: 2.1

docker_auth: &docker_auth
  username: $DOCKERHUB_USERNAME
  password: $DOCKERHUB_PASSWORD

defaults: &defaults
  docker:
    - image: greenpeaceinternational/p4-builder:latest
      auth:
        <<: *docker_auth

jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: configure
          command: |
            mkdir -p /tmp/workspace/var
            echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
      - run:
          name: prepare
          command: make prepare
      - run:
          name: lint
          command: make lint
      - run:
          name: build
          command: make build
      - run:
          name: dockerhub login
          command: docker-login.sh
      - run:
          name: push
          command: make -j2 push
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var

workflows:
  branch:
    jobs:
      - build:
          context: org-global
